// This file is auto-generated. Do not edit manually.
export const assetMap = {
  "1.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/1.jpeg",
  "2.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/2.jpeg",
  "3.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/3.jpeg",
  "4.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/4.jpeg",
  "5.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/5.jpeg",
  "6.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/6.jpeg",
  "7.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/7.jpeg",
  "mal.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/mal.jpeg",
  "mal2.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/mal2.jpeg",
  "pukit.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/pukit.jpeg",
  "barba.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/barba.jpeg",
  "anti.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/anti.jpeg",
  "AdobeStock_1177211600.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_1177211600.jpeg",
  "AdobeStock_1190616071.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_1190616071.jpeg",
  "AdobeStock_123306802.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_123306802.jpeg",
  "AdobeStock_168390423.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_168390423.jpeg",
  "AdobeStock_216195684.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_216195684.jpeg",
  "AdobeStock_312484778.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_312484778.jpeg",
  "AdobeStock_409579813.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_409579813.jpeg",
  "AdobeStock_409579813(1).jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_409579813(1).jpeg",
  "AdobeStock_494092930.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/AdobeStock_494092930.jpeg",
  "logo.png": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/logo.png",
  "trustpilot.png": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/trustpilot.png",
  "react.svg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/react.svg",
  "vite.svg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/vite.svg",
  "ATOL logo.png": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/ATOL%20logo.png",
  "IATA logo.png": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/IATA%20logo.png",
  "ABTA logo.png": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/ABTA%20logo.png",
  "Antigua pics/1.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Antigua%20pics/1.jpeg",
  "Antigua pics/2.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Antigua%20pics/2.jpeg",
  "Antigua pics/3.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Antigua%20pics/3.jpeg",
  "Antigua pics/4.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Antigua%20pics/4.jpeg",
  "Antigua pics/5.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Antigua%20pics/5.jpeg",
  "Antigua pics/6.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Antigua%20pics/6.jpeg",
  "Antigua pics/7.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Antigua%20pics/7.jpeg",
  "Maldives pic/1.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/1.jpeg",
  "Maldives pic/2.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/2.jpeg",
  "Maldives pic/3.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/3.jpeg",
  "Maldives pic/4.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/4.jpeg",
  "Maldives pic/5.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/5.jpeg",
  "Maldives pic/6.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/6.jpeg",
  "Phuket pictures/1.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Phuket%20pictures/1.jpeg",
  "Phuket pictures/2.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Phuket%20pictures/2.jpeg",
  "Phuket pictures/3.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Phuket%20pictures/3.jpeg",
  "Phuket pictures/4.jpeg": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Phuket%20pictures/4.jpeg",
  "1.mov": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/1.mov",
  "2.mov": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/2.mov",
  "Maldives pic/AdobeStock_497305559.mov": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/AdobeStock_497305559.mov",
  "Maldives pic/AdobeStock_507998705.mov": "https://airworldtour.s3.eu-north-1.amazonaws.com/assets/Maldives%20pic/AdobeStock_507998705.mov"
}; 